apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "meshcentral.fullname" . }}-scripts
  labels:
    {{- include "meshcentral.labels" . | nindent 4 }}
data:
  entrypoint.sh: |
    {{- .Files.Get "scripts/entrypoint.sh" | nindent 4 }}
  setup-mesh.sh: |
    {{- .Files.Get "scripts/setup-mesh.sh" | nindent 4 }}
  manage-service.sh: |
    {{- .Files.Get "scripts/manage-service.sh" | nindent 4 }}
