apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-default
data:
  OPENFRAME_MODE: "true"
  OPENFRAME_GATEWAY_URL: "localhost"

  MESH_PROTOCOL: "ws"
  MESH_DEVICE_GROUP: "OpenFrame"
  MESH_EXTERNAL_PORT: {{ .Values.config.settings.port | default 4430 | quote }}
 
---

{{- if not .Values.mongodb.existingConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-mongodb-config
  labels:
    {{- include "meshcentral.labels" . | nindent 4 }}
data:
  MC_MONGO_HOSTS: {{ .Values.mongodb.hostsValue | quote }}
  MC_MONGO_DATABASE: {{ .Values.mongodb.databaseValue | quote }}
  MC_MONGO_AUTH_SOURCE: {{ .Values.mongodb.authSourceValue | quote }}
  MC_MONGO_REPLICA_SET: {{ .Values.mongodb.replicaSetValue | quote }}
  MC_MONGO_URI_OPTIONS: {{ .Values.mongodb.uriOptionsValue | quote }}
{{- end }}
