apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "meshcentral.fullname" . }}-scripts
  labels:
    {{- include "meshcentral.labels" . | nindent 4 }}
data:
  entrypoint.sh: |
    {{- .Files.Get "scripts/entrypoint.sh" | nindent 4 }}
