apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "meshcentral.fullname" . }}
  labels:
    {{- include "meshcentral.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "meshcentral.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        checksum/scripts: {{ include (print $.Template.BasePath "/configmap-scripts.yaml") . | sha256sum }}
        checksum/env: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/credentials: {{ include (print $.Template.BasePath "/secret-credentials.yaml") . | sha256sum }}
      labels:
        {{- include "meshcentral.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsUser: {{ .Values.securityContext.runAsUser }}
      containers:
        - name: meshcentral
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/scripts/entrypoint.sh"]
          ports:
            - name: http
              containerPort: {{ .Values.config.settings.port | default 4430 }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "meshcentral.fullname" . }}-env
            - secretRef:
                name: {{ include "meshcentral.fullname" . }}-credentials
          startupProbe:
            {{- toYaml .Values.startupProbe | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /opt/mesh
            - name: config
              mountPath: /tmp/config
              readOnly: true
            - name: scripts
              mountPath: /scripts
              readOnly: true
      volumes:
        - name: config
          secret:
            secretName: {{ include "meshcentral.fullname" . }}-config
        - name: scripts
          configMap:
            name: {{ include "meshcentral.fullname" . }}-scripts
            defaultMode: 0755
        - name: data
          emptyDir: {}
