{{- if not .Values.credentials.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-credentials
  labels:
    {{- include "meshcentral.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.credentials.meshUserKey }}: {{ .Values.credentials.meshUserValue | quote }}
  {{ .Values.credentials.meshPassKey }}: {{ .Values.credentials.meshPassValue | quote }}
  {{ .Values.credentials.meshConfigKeyKey }}: {{ .Values.credentials.meshConfigKeyValue | quote }}
{{- end }}

---
{{- if not .Values.mongodb.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-mongodb-creds
  labels:
    {{- include "meshcentral.labels" . | nindent 4 }}
type: Opaque
stringData:
  MC_MONGO_USER: {{ .Values.mongodb.userValue | quote }}
  MC_MONGO_PASSWORD: {{ .Values.mongodb.passwordValue | quote }}
{{- end }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-config
type: Opaque
stringData:
  config.json: |
    {{- .Values.config | toPrettyJson | nindent 4 }}
