apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-config
  labels:
    {{- include "meshcentral.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.json: |
    {{- .Values.config | toPrettyJson | nindent 4 }}
