apiVersion: v1
kind: Secret
metadata:
  name: {{ include "meshcentral.fullname" . }}-credentials
  labels:
    {{- include "meshcentral.labels" . | nindent 4 }}
type: Opaque
stringData:
  MESH_USER: {{ .Values.credentials.meshUser | quote }}
  MESH_PASS: {{ .Values.credentials.meshPass | quote }}
  MESH_CONFIG_KEY: {{ .Values.credentials.meshConfigKey | quote }}
