apiVersion: v2
name: meshcentral
description: MeshCentral - full computer management web site
type: application
version: 0.0.1
appVersion: "0.0.1"
keywords:
  - meshcentral
  - remote-management
  - remote-desktop
home: https://meshcentral.com
sources:
  - https://github.com/Ylianst/MeshCentral
maintainers:
  - name: flamingo
