flowchart TD
    BeforeInit --> AfterInit
    AfterInit --> BeforeUpdate
    BeforeUpdate --> BeforeDatasetsUpdate
    BeforeDatasetsUpdate --> AfterDatasetsUpdate
    AfterDatasetsUpdate --> BeforeDraw
    BeforeDraw --> AfterDraw
