flowchart TD
    ChartCoreUtilities["Chart Core Utilities"] --> ChartCoreLogic["Chart Core Logic"]
    ChartCoreLogic --> ChartCoreExtensionsMain["Chart Core Extensions Main"]
    ChartCoreExtensionsUtilities["Chart Core Extensions Utilities"] --> ChartCoreExtensionsMain
    ChartCoreExtensionsMain --> ChartCoreExtensions["Chart Core Extensions"]
