flowchart LR
    ChartRegistry["Registry"]
    Controllers["Controllers"]
    Elements["Elements"]
    Scales["Scales"]
    Plugins["Plugins"]

    ChartRegistry --> Controllers
    ChartRegistry --> Elements
    ChartRegistry --> Scales
    ChartRegistry --> Plugins
