flowchart TD
    AggregatedValue["Aggregated Value"] --> CompareMin["Compare With Current Min"]
    CompareMin --> UpdateMin["Update Min"]
    AggregatedValue --> CompareMax["Compare With Current Max"]
    CompareMax --> UpdateMax["Update Max"]
