sequenceDiagram
    participant Server
    participant BrowserSocket
    participant Websock
    participant RFB

    Server->>BrowserSocket: Binary Frame
    BrowserSocket->>Websock: onmessage
    Websock->>Websock: Buffer into rQ
    Websock->>RFB: message()
    RFB->>Websock: rQshift*
