flowchart TD
    Terminal --> EventEmitter
    EventEmitter --> AccessibilityManager
    EventEmitter --> Linkifier
    EventEmitter --> RenderService
    EventEmitter --> Viewport
    EventEmitter --> SelectionService
