flowchart TD
    Terminal["Terminal"] --> AccessibilityManager
    Terminal --> Linkifier
    Terminal --> RenderService
    Terminal --> SelectionService

    SelectionService --> AccessibilityManager
    RenderService --> Linkifier
