flowchart TD
    Instantiation["InstantiationService"]
    Terminal --> Instantiation
    Instantiation --> BufferService
    Instantiation --> CoreService
    Instantiation --> RenderService
    Instantiation --> SelectionService
    Instantiation --> MouseService
    Instantiation --> ThemeService
